### ISSUE TITLE
Bajar accesiones para México de GeneBank y BOLD

### ISSUE THREAD

**Issue by lmalpicas** [AliciaMstt/GeoGenMX#3]
Me di cuenta al comparar  los registros de BOLD con los de NCBI que hay algunos registros de NCBI que deberian haberse descargado porque entraban en los parametros de busqueda, no se descargaron, me falta checar si tambien paso eso con los de BOLD y arreglar la busqueda de NCBI.

**Comment by AliciaMstt** [comment]
Graciar por avisar. No entiendo bien por qué sucede. ¿Tu ya lo tienes claro?

**Comment by lmalpicas** [comment]
Parece que eran las comillas si pongo '/country="Mexico"', y si pongo /country="Mexico" o /country=Mexico todos funcionan, pero el primero me regresa matches parciales de la frase y los otros dos solo matches exactos, eso parece, aunque lo que se me hace raro y no entiendo porque, es que al hacer el uniq lo que me salia eran dos:
Mexico
Mexico, Xalapa, Jardin Botanico

El segundo no entiendo porque si lo capturo y los otros que tienen info. del estado o la región no. Ya mande a keri los scripts con esa correccion y lo que pude ver si estaba jalando datos que decían, Michoacán, Yucatán y Quintana Roo.

**Comment by AliciaMstt** [comment]
Imagino que puede tener que ver con que toma como distinto el término Mexico a secas que si además tiene info de ciudad y estados. Lo único que me preocupa es que hacer una búsqueda parcial jale tmb datos de New Mexico. Checa que no ocurra eso.  Si sí ocurre, tal vez una solución podría ser buscar Mexico y explícitamente excluir New Mexico con un NOT.

**Comment by lmalpicas** [comment]
Yo creo que si las va a descargar, yo creo que excluir con el NOT es la opción. ya hice la prueba y me sale esto: 
'/country="New Mexico"'  46761 resultados 
'/country="USA: New Mexico"'  24993 resultados
y el total sin excluir nada:  954690 resultados
No se cual de las dos usar, pensaba usar el de USA: New Mexico y de ahi volver a checar con un grep el output a ver que son esas que dicen New Mexico sin el USA para que no se nos vaya nada.

**Comment by lmalpicas** [comment]
Corregí lo de New Mexico y lo mandé a la cola de keri para descargar los datos completos. También estoy intentando descargar en mi compu al menos el archivo que excluye bacterias, archaeas, etc.

**Comment by AliciaMstt** [comment]
Excelente. Muchas gracias.

**Comment by AliciaMstt** [comment]
Ya podemos cerrar este issue
