### ISSUE TITLE
Resumen exploratorio de tipo de secuencias y taxa obtenidos por el punto anterior

### ISSUE THREAD

**Issue by lmalpicas** [AliciaMstt/GeoGenMX#4]

**Comment by lmalpicas** [comment]
Por el momento dividí el repo en dos carpetas, una con los scripts para BOLD y otra con los scripts para genebank. En el README de la carpeta de BOLD ya viene detallado como se obtuvieron los datos, la información taxonómica de NCBI Taxonomy, las primeras gráficas así como la separación de los datos en los que tienen latitud y longitud y los que no tienen. Esto está en proceso para los scripts de GENEBANK.

**Comment by AliciaMstt** [comment]
Me late la división. 

Está bien el md que hiciste dentro de cada carpeta. Los resumenes que siguen sería mejor hacerlos en inglés de una vez, si te parece bien. Si te toma mucho tiempo, luego traducimos la versión final.
